# Use NodeJS on flexible app engine
runtime: nodejs
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "20"

# Only use one instance
manual_scaling:
  instances: 1

# Use low resources during development and testing
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  BACKEND: "https://southampton-guesser-functions-awdkf4e5crf8b8bd.francecentral-01.azurewebsites.net"
  DURABLE_FUNCTIONS_ENDPOINT: "https://southampton-guesser-durable-abehdmf6ccdteng7.francecentral-01.azurewebsites.net/api"
  SIGNALR_ENDPOINT: "https://southampton-guesser-signalr.service.signalr.net"
  BACKEND_KEY: "=="
  DURABLE_FUNCTIONS_KEY: "-=="